name: Make sure Jekyll can build the page

on: [push, pull_request]

jobs:
  jekyll:
    name: Build Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1
